# This is a basic workflow to help you get started with Actions

name: genpatch

# Controls when the workflow will run
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: 134.0.6998.88
      SRCDIR: chromium-src
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Checkout
        uses: actions/checkout@v4

      - name: "remove not needed items"
        run: |
          sudo rm -rf /usr/local/.ghcup \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/share/powershell \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache/CodeQL \
            /imagegeneration \
            "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Download and extract rpm
        run: |
          cd $SRCDIR
          wget https://kojipkgs.fedoraproject.org//packages/chromium/$VERSION/1.el9/src/chromium-$VERSION-1.el9.src.rpm
          rpm2cpio chromium-$VERSION-1.el9.src.rpm | cpio -i
          ls -lsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-patches-${{ env.VERSION }}
          path: /home/runner/work/gollum/gollum/chromium-src/*.patch
