name: partbuild-windows

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    runs-on: windows-latest
    env:
      VERSION: 134.0.6998.118
      SRCDIR: chromium-src
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup src dir
        run: |
          mkdir -p $SRCDIR && cd $SRCDIR
          cat > .gclient <<EOF
          solutions = [
            {
              "name": "src",
              "url": "https://chromium.googlesource.com/chromium/src.git@$VERSION",
              "managed": False,
              "custom_deps": {},
              "custom_vars": {},
            },
          ]
          target_os = ["linux"]
          EOF

      - name: Clone depot_tools
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd $SRCDIR
          cat .gclient
          echo "Clone depot_tools..."
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools
          echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"

      - name: Clone source and do gclient sync
        shell: bash
        run: |
          cd $SRCDIR
          echo "PATH: $PATH"
          echo "gclient sync chromium-$VERSION..." 
          gclient sync --no-history --nohooks
          du -sh ../$SRCDIR
          gclient runhooks
          src/build/util/lastchange.py -o src/build/util/LASTCHANGE
          src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h
          src/build/util/lastchange.py -m SKIA_COMMIT_HASH -s src/third_party/skia --header src/skia/ext/skia_commit_hash.h
          src/build/util/lastchange.py -s src/third_party/dawn --revision src/gpu/webgpu/DAWN_VERSION
          cd src && mkdir -p out/Release
          cd out/Release
          wget -O args.gn https://raw.githubusercontent.com/COD3HUNT3R/gollum/refs/heads/main/linux-args.gn
          cd ../..
          sudo apt install -y ninja-build gperf
          gn gen out/Release
          rm -rf .git

      - name: Build base
        shell: bash
        run: |
          cd $SRCDIR/src
          autoninja -C out/Release base

      - name: Build content/public/common
        shell: bash
        run: |
          cd $SRCDIR/src
          autoninja -C out/Release content/public/common

      - name: Compress artifacts
        shell: bash
        run: |
          cd $SRCDIR/src
          ZSTD_CLEVEL=12 tar -I zstd -cvpf /home/runner/work/gollum/gollum/chromium-src/out.tar.zst ./out
          cd ..
          wget https://raw.githubusercontent.com/COD3HUNT3R/gollum/refs/heads/main/export_tarball.py
          chmod +x export_tarball.py
          ./export_tarball.py --version --xz --remove-nonessential-files chromium-$VERSION --progress --src-dir src/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chromium-src
          path: |
            /home/runner/work/gollum/gollum/chromium-src/*.tar.xz
            /home/runner/work/gollum/gollum/chromium-src/out.tar.zst

  build2:
    needs: build1
    runs-on: windows-latest
    env:
      VERSION: 134.0.6998.118
      SRCDIR: chromium-src
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chromium-src
          path: /home/runner/work/gollum/gollum/chromium-src

      - name: Clone depot_tools
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd $SRCDIR
          echo "Clone depot_tools..."
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools
          echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"
          sudo apt install -y ninja-build gperf

      - name: Extract tar
        shell: bash
        run: |
          cd $SRCDIR && ls -lsh
          tar -xf chromium-$VERSION.tar.xz
          tar -xf out.tar.zst
          ls -lsh
          rm -f chromium-$VERSION.tar.xz out.tar.zst
          mv out chromium-$VERSION && cd chromium-$VERSION
          pwd && ls -lsh

      - name: Build content/public/browser
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release content/public/browser

      - name: Build chrome/gpu
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release chrome/gpu

      - name: Compress artifacts
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          ZSTD_CLEVEL=12 tar -I zstd -cvpf /home/runner/work/gollum/gollum/chromium-src/out.tar.zst ./out
          cd ..
          wget https://raw.githubusercontent.com/COD3HUNT3R/gollum/refs/heads/main/export_tarball.py
          chmod +x export_tarball.py
          ./export_tarball.py --version --xz --remove-nonessential-files chromium-$VERSION --progress --src-dir chromium-$VERSION/

      - name: Delete existing artifact to prevent conflicts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: chromium-src

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chromium-src
          path: |
            /home/runner/work/gollum/gollum/chromium-src/*.tar.xz
            /home/runner/work/gollum/gollum/chromium-src/out.tar.zst

  build3:
      needs: build2
      runs-on: windows-latest
      env:
        VERSION: 134.0.6998.118
        SRCDIR: chromium-src
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chromium-src
          path: /home/runner/work/gollum/gollum/chromium-src

      - name: Clone depot_tools
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd $SRCDIR
          echo "Clone depot_tools..."
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools
          echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"
          sudo apt install -y ninja-build gperf

      - name: Extract tar
        shell: bash
        run: |
          cd $SRCDIR && ls -lsh
          tar -xf chromium-$VERSION.tar.xz
          tar -xf out.tar.zst
          ls -lsh
          rm -f chromium-$VERSION.tar.xz out.tar.zst
          mv out chromium-$VERSION && cd chromium-$VERSION
          pwd && ls -lsh

      - name: Build chrome_java
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release chrome_java

      - name: Build chrome/common
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release chrome/common

      - name: Build chrome/browser
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release chrome/browser

      - name: Build chrome
        shell: bash
        run: |
          cd $SRCDIR/chromium-$VERSION
          autoninja -C out/Release chrome
          autoninja -C out/Release chrome_sandbox
          autoninja -C out/Release chromedriver
          autoninja -C out/Release installer
          ls -lsh out/Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: /home/runner/work/gollum/gollum/chromium-src/chromium-$VERSION/out/Release/*.rpm
